#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_zsh_files() {

    local file=""
    local i=""

    declare -a FILES_TO_SOURCE
    FILES_TO_SOURCE=(
        "zsh.local"  # for local settings that should
                      # not be under version control
    )
    declare -r FILES_TO_SOURCE

    for i in ${FILES_TO_SOURCE[@]}; do

        file="$HOME/.$i"

        [ -r "$file" ] \
            && source "$file"

    done

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_zsh_files
unset -f source_zsh_files

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear system messages (e.g.: system copyright notice, the
# date and time of the last login, the message of the day, etc.)

clear
